//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Printer.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Картриджи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Картриджи()
        {
            this.Принтеры = new HashSet<Принтеры>();
        }
    
        public int id_картриджа { get; set; }
        public string Название { get; set; }
        public string Тип_картриджа { get; set; }
        public string Статус { get; set; }
        public System.DateTime Дата_заправки { get; set; }
        public string Количество_заправок { get; set; }
        public Nullable<int> id_тонер { get; set; }
    
        public virtual Тонер Тонер { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Принтеры> Принтеры { get; set; }
    }
}
