//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Printer.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Принтеры
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Принтеры()
        {
            this.Ремонт = new HashSet<Ремонт>();
        }
    
        public int id_принтера { get; set; }
        public string Инвентарный_номер { get; set; }
        public string Модель_принтера { get; set; }
        public string Тип_принтера { get; set; }
        public Nullable<int> id_поставщика { get; set; }
        public string Гарантия { get; set; }
        public System.DateTime Дата_покупки { get; set; }
        public System.DateTime Дата_списания { get; set; }
        public Nullable<int> id_картриджи { get; set; }
        public string Статус { get; set; }
        public Nullable<int> id_ответственные { get; set; }
        public string Кабинет { get; set; }
    
        public virtual Картриджи Картриджи { get; set; }
        public virtual Ответственные Ответственные { get; set; }
        public virtual Поставщики Поставщики { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ремонт> Ремонт { get; set; }
    }
}
